"""Code file analysis: shebang, imports, minification, generated markers."""

import re
from ..signals import AnalysisContext, Signal
from ..taxonomy import *  # noqa: F403, F401

GENERATED_MARKERS = [
    "generated by", "auto-generated", "do not edit",
    "this file is generated", "@generated", "code generated",
    "automatically generated", "autogenerated",
]


def analyze(ctx: AnalysisContext):
    """Analyze potential code/text files."""
    ext = ctx.extension

    # Only analyze text-like files
    if ctx.true_category not in ("code", "text", None):
        # If it's "other" with a code extension, still analyze
        if ctx.true_category == "other" and ext not in (
            set().union(CODE_EXTENSIONS, CONFIG_EXTENSIONS)
        ):
            return

    # Notebook is clear from extension
    if ext == "ipynb":
        ctx.signals.append(Signal("notebook_ext", ext, {CODE_NOTEBOOK: 0.7}))
        return

    # Try to read first 8KB
    try:
        with open(ctx.path, "r", encoding="utf-8", errors="ignore") as f:
            content_head = f.read(8192)
    except (OSError, PermissionError):
        return

    if not content_head.strip():
        return

    lines = content_head.split("\n")

    # Shebang
    if lines and lines[0].startswith("#!"):
        ctx.signals.append(Signal("shebang", lines[0], {
            CODE_SCRIPT: 0.35,
        }))

    # Generated file markers
    head_lower = content_head[:2000].lower()
    for marker in GENERATED_MARKERS:
        if marker in head_lower:
            ctx.signals.append(Signal("generated_marker", marker, {
                CODE_GENERATED: 0.5,
            }))
            break

    # Minification detection
    non_empty = [l for l in lines if l.strip()]
    if non_empty:
        avg_len = sum(len(l) for l in non_empty) / len(non_empty)
        max_len = max(len(l) for l in non_empty)

        if avg_len > 500 or (max_len > 5000 and len(non_empty) < 10):
            ctx.signals.append(Signal("minified_code", avg_len, {
                CODE_MINIFIED: 0.6,
            }))

    # Import/function density → real source code
    import_count = sum(
        1 for l in lines
        if re.match(r'^\s*(import |from |require\(|#include|using |use )', l)
    )
    func_count = sum(
        1 for l in lines
        if re.match(r'^\s*(def |function |fn |func |pub fn |public |private |class |struct |interface )', l)
    )

    if import_count > 2 or func_count > 1:
        ctx.signals.append(Signal("source_structure", {
            "imports": import_count, "functions": func_count
        }, {
            CODE_SOURCE: 0.3,
        }))

    # Large data files
    if ext in ("json", "xml", "csv"):
        if ctx.file_size > 100_000:
            ctx.signals.append(Signal("large_data_file", ctx.file_size, {
                CODE_DATA: 0.4,
            }))

    # Config detection from extension (supplement filename_patterns)
    if ext in CONFIG_EXTENSIONS:
        ctx.signals.append(Signal("config_extension", ext, {
            CODE_CONFIG: 0.3,
        }))
